version: "2.2"

services:

  web:

    build:

      context: .

      dockerfile: Dockerfile_web

    container_name: web-app

    ports:

      - "80:80"

      - "3306:3306"

    environment:

    # specifies Adminer account and password for web login database.

      USER: "root"

      PASSWD: "123456"

      BIND_ADDRESS: "false"

    volumes:

      - ./data/www:/app/zentaopms

      - ./data/data:/var/lib/mysql

    #restart: always


  config:

    build:

      context: .

      dockerfile: Dockerfile_config

    container_name: config-app
   
    environment:
 
      - PYTHONIOENCODING=utf-8

    depends_on:

      - web

    volumes: 

      - "./config/:/opt/config/"

    entrypoint: /opt/config/autoscript.sh


  poc:

    build:

      context: .

      dockerfile: Dockerfile_poc

    container_name: poc-app
    
    environment:
 
      - PYTHONIOENCODING=utf-8

    depends_on:

      - web
      - config

    volumes: 

      - "./poc/:/opt/poc/"

    entrypoint: /opt/poc/autoscript.sh
